
#### Data

[Glocal alcohol consumption dataset](https://github.com/rfordatascience/tidytuesday/blob/master/data/2018/2018-06-26/week13_alcohol_global.csv).

This data shows the beer, spirit and wine servings and total litres of pure alcohol by country. The data source is from Thomas Mock (2022). Tidy Tuesday: A weekly data project aimed at the R ecosystem [https://github.com/rfordatascience/tidytuesday](https://github.com/rfordatascience/tidytuesday). 

##### Variables:

- country : country name.

- beer_servings : beer servings.

- spirit_servings : spirit servings.

- wine-servings : wine servings.

- total_litres_of_pure_alcohol : the total (sum of recorded and unrecorded alcohol) amount of alcohol consumed per person (15 years of age or older) over a calendar year, in litres of pure alcohol, adjusted for tourist consumption. (The World Bank Group,2022)



#### Purpose

The purpose of the app is to:

1. Show global alcohol consumption, which could reflect the economy of country.

2. Show comparison of global alcohol consumption by alcohol, which could reflect the culture of country.

3. Reflect the alcoholism of people.

This app shows global beer, spirit and wine servings distribution and global alcohol consumption. And this app could help users to see alcohol consumption map by countries by personalized choice.

#### Creator

Di Cui (dcui0002@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
